#!/bin/bash

H=`hostname`
DI=`route -n | grep UG | awk '{print $8}'`
IP=`ip addr show ${DI} | grep "inet.*${DI}" | awk '{print $2}'`

echo
echo -n "  Welcome to "
echo -en "\E[47;34m${H}\033[1m\033[0m"
tput sgr0
echo " (${IP} via ${DI})"
