.IX Title "UPDATE-MOTD 1"
.TH UPDATE-MOTD 1 "2011-01-20" update-motd update-motd

.SH "NAME"
update\-motd \- Automatically generate the message-of-the-day (MOTD)

.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
update\-motd

.SH "DESCRIPTION"
.IX Header "DESCRIPTION"

\fBupdate-motd\fP is a script that will dynamically print a message-of-the-day according to the output of scripts installed by the administrator in \fI/etc/update-motd.d\fP.

.SH FILES
\fI/etc/update-motd.d/\fP, \fI/etc/motd\fP

.SH "AUTHOR"
.IX Header "AUTHOR"
Robert Olejnik <robert@teonite.com>

.SH "LICENSE"
.IX Header "LICENSE"
This manpage and the \fBupdate-motd\fP utility  was  written  by Robert Olejnik <robert@teonite.com>.  Permission is granted to copy, distribute and/or modify  this  document  under the terms of the GNU General Public License, Version 3 or any later version published by the Free  Software  Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-3.
